[windows]
X1-YOGA ansible_host=X1-YOGA.local
# X1-CARBON ansible_host=X1-CARBON.local

[windows:vars]
ansible_connection=ssh
ansible_shell_type=powershell
ansible_port=22
# User will be authenticated via Semaphore Key Store (SSH Key or Password)
ansible_user=kylehase
